[package]
name = "rogue"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
log = "0.4.29"
once_cell = "1.21.3"
rand = "0.9.2"
simple_logger = "5.1.0"
thiserror = "2.0.17"
