[package]
name = "rogue"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
env_logger = "0.11.8"
log = "0.4.29"
once_cell = "1.21.3"
rand = "0.9.2"
thiserror = "2.0.17"
